# Generated by Django 5.0.9 on 2024-09-30 06:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=255)),
                ('sub_course', models.CharField(max_length=200)),
                ('module', models.CharField(max_length=200)),
                ('sub_module', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('img_list', models.TextField(null=True)),
                ('video_url', models.TextField(null=True)),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
