# Generated by Django 5.0.9 on 2024-09-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='content',
            new_name='content_html_list',
        ),
    ]
