# Generated by Django 5.0.9 on 2024-09-30 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_content_course_content_html_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='content_html_list',
            new_name='content',
        ),
    ]
